on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_IP_ADDRESS }}
          port: ${{ secrets.FTP_PORT }}
          sftp_only: true
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './*'
          remote_path: ${{ secrets.FTP_DIR }}
          delete_remote_files: false
